#train_win05:
#  _target_: src.datasets.AudioDataset
#  sampling_rate: 16000
#  window_size: 0.5
#  name: "train-clean-100"
#train_full:
#  _target_: src.datasets.AudioDataset
#  sampling_rate: 16000
#  window_size: null
#  base_factor: 200
#  name: "train-clean-100"
#
#test_win05:
#  _target_: src.datasets.AudioDataset
#  sampling_rate: 16000
#  window_size: 0.5
#  base_factor: 200
#  custom_index: True
#  name: "test-clean"

test_full:
  _target_: src.datasets.AudioDataset
  sampling_rate: 16000
  window_size: null
  base_factor: 200
  name: "test-clean"
