device: "auto"
train: [ ]  # metrics that are calculated during training
# just an example to see difference
inference:
  - _target_: src.metrics.STOIMetric
    sampling_rate: 16000
    device: ${metrics.device}
    name: "STOI"

  - _target_: src.metrics.NISQAMetric
    sampling_rate: 16000
    device: ${metrics.device}
    name: "NISQA"
#  - _target_: src.metrics.ExampleMetric
#    metric:
#      _target_: torchmetrics.classification.MulticlassAccuracy
#      num_classes: 10
#    device: ${metrics.device}
#    name: "MulticlassAccuracy"
#  - _target_: src.metrics.ExampleMetric
#    metric:
#      _target_: torchmetrics.classification.MulticlassAccuracy
#      num_classes: 10
#    device: ${metrics.device}
#    name: "MulticlassAccuracy2.0"
