defaults:
  - model: soundstream
  - writer: cometml
  - metrics: baseline
  - datasets: librispeech_onebatchtest
  - dataloader: baseline
  - transforms: baseline
  - _self_
optimizer:
  gen:
    _target_: torch.optim.AdamW
    lr: 3e-4
  discr:
    _target_: torch.optim.AdamW
    lr: 3e-4

lr_scheduler:
  gen:
    _target_: torch.optim.lr_scheduler.StepLR
    gamma: 0.97
    step_size: ${trainer.epoch_len}
  discr:
    _target_: torch.optim.lr_scheduler.StepLR
    gamma: 0.95
    step_size: ${trainer.epoch_len}

loss_function:
  gen:
    _target_: src.loss.GeneratorLoss
    l_adv: 0.1
    l_feat: 10
    l_rec: 1
    rec_n_mels: 64
  discr:
    _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: 100
  max_grad_norm: 100
  device_tensors: [ "orig" ] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
