defaults:
  - model: soundstream
  - metrics: baseline
  - datasets: librispeech_full # we do not want to run inference on training data
  - dataloader: baseline
  - transforms: baseline
  - _self_
inferencer:
  device_tensors: [ "orig" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "infer" # any name here, can be a dataset name
  seed: 1
  eval_batch_size: 16
  from_pretrained: "saved/gan_training_bit6_200ep_0.5s_mixed_loss_C32_great/model_best.pth" # path to the pretrained model
