defaults:
  - model: soundstream
  - metrics: baseline
  - datasets: librispeech_onebatchtest # we do not want to run inference on training data
  - dataloader: baseline
  - transforms: baseline
  - _self_
inferencer:
  device_tensors: [ "orig" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "infer" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/testing/checkpoint-epoch40.pth" # path to the pretrained model
